Refactored SU Flavor logic
CCI-MOC/openstack-billing-from-db pull request #64
Opened 2024-05-20 17:29 UTC by QuanMPhm

Closes #57. The Flavor object will no longer require an SU name. The SU type will be determined only from PCI requests.

2024-05-28 18:54 UTC, knikolla requested changes
Looks good besides 1 comment.

2024-05-28 18:54 UTC, knikolla commented on src/openstack_billing_db/model.py
> +                if count == "1m":
You're never going to get "1m" here and you can safely drop this case. That "1m" was part of the flavor name, when we were detecting the gpu count based on the last part of the flavor name.

2024-05-28 18:57 UTC, knikolla commented
> @knikolla I'm a bit unsure about how to write a test case for this PR. From what I understand, because I want to test the correctness of my code, do I make test cases around calling `collect_invoice_data_from_openstack()` and `Database.get_instances()`, since those are the functions that are changed?

The service unit type is detected from the contents of `pci_requests` right? You can split out that part into a separate function and see that it detects the appropriate service unit types based on the provided pci_request that you are crafting. 

Similarly, the function that sums up based on flavor type, does it based on the su type value.

So the trick to testing this is to split out as a separate what can be written as a separate function and that doesn't have dependencies on external systems.

2024-06-20 18:20 UTC, naved001 commented on src/openstack_billing_db/model.py
> +            raise Exception("Pci request list empty")
why does the error message say "list empty" when the condition checks for that the length is more than 1? The old code didn't have this message.

2024-06-20 18:20 UTC, naved001 commented on src/openstack_billing_db/model.py
> +                gpu_count=count,
if the service_unit_type is cpu, then `count` is never defined and this will complain.

2024-06-21 02:59 UTC, QuanMPhm commented
@naved001 I've applied your comments, and renamed the `count` variable to `gpu_count` for clarity.

2024-06-21 15:49 UTC, naved001 requested changes

2024-06-21 15:49 UTC, naved001 commented on src/openstack_billing_db/model.py
> +        su_type = f"gpu_{pci_name}"
if `pci_name` is `a100-sxm4`, then the su_type becomes `gpu_a100-sxm4`. And that's fine, but then later on when `set_invoice_su_hours` is called with this service unit type, we set `su_hours_attr`
```
su_hour_attr = f"{service_unit_type}_su_hours"
```
and in this case it'll become `gpu_a100-smx4_su_hours`, and then we check if this attribute exists but it'll fail because the attribute is called `gpu_a100sxm4_su_hours`. Notice that there's no `-`.  

So, that needs to be fixed and please add a test for the same.

2024-07-08 13:49 UTC, QuanMPhm commented on src/openstack_billing_db/model.py
> +        su_type = f"gpu_{pci_name}"
@naved001 Sorry for the late response. I missed this comment. 

If this is the case, my solution would have been to strip the `pci_name` of any `-` characters, but the problem then becomes whether or not this would be a valid way to filter for every `alias_name` in the future. Would do you think?

2024-07-26 13:15 UTC, joachimweyl commented on src/openstack_billing_db/model.py
> +        su_type = f"gpu_{pci_name}"
@naved001 is this conversation resolved?

2024-08-02 18:27 UTC, naved001 commented on src/openstack_billing_db/model.py
> +        su_type = f"gpu_{pci_name}"
@knikolla thoughts on this? We'll have to either update the gpu su_type for A100-SXM4 to include the `-`, or strip the `-` right here.

2024-09-26 18:14 UTC, knikolla commented on src/openstack_billing_db/model.py
> +        su_type = f"gpu_{pci_name}"
I'm okay with stripping the `-`. Sorry for the late response.

2024-09-30 14:41 UTC, QuanMPhm commented on src/openstack_billing_db/model.py
> +        su_type = f"gpu_{pci_name}"
I have implemented stripping the `-` and modified the test case accordingly

2024-09-30 14:45 UTC, naved001 approved these changes

2024-09-30 15:18 UTC, knikolla reviewed
Looks good, will merge later in the week after we're done with processing September.

2024-10-02 14:33 UTC, knikolla approved these changes

2024-10-02 14:34 UTC, merged