Implemeted `nerc-rates` repo into Openstack billing
CCI-MOC/openstack-billing-from-db pull request #71
Opened 2024-06-13 07:58 UTC by QuanMPhm

Closes #70.

2024-06-13 20:18 UTC, larsks approved these changes

2024-06-13 20:19 UTC, larsks approved these changes

2024-06-17 20:08 UTC, naved001 requested changes
@QuanMPhm This PR does not make it clear in the commit message that 2 arguments still need to be supplied via the command line instead of nerc-rates. It also doesn't mention a reason anywhere.

But anyway, I have proposed in the comments that we get those 2 remaining arguments from `nerc-rates` as well.

2024-06-17 20:08 UTC, naved001 commented on src/openstack_billing_db/main.py
> +            include_stopped_runtime=args.include_stopped_runtime,
there's a flag for that in `rates.yaml` for this. Please use that.  

```
>>> rates.get_value_at("Charge for Stopped Instances", "2023-06")
'False'
>>> rates.get_value_at("Charge for Stopped Instances", "2024-06")
'True'
```

2024-06-17 20:09 UTC, joachimweyl commented on src/openstack_billing_db/main.py
> +            gpu_a2=args.rate_gpu_a2_su,
We should be using rates.yaml as much as possible.

2024-06-18 05:23 UTC, QuanMPhm commented on requirements.txt
> +git+https://github.com/CCI-MOC/nerc-rates@74eb4a7#egg=nerc_rates
I picked this commit since I saw that we usually pin commits when listing our other python repos as a requirement. Now that you mention it, I see that it makes sense to not pin a commit and just use the latest version of `nerc-rates`.

2024-06-18 05:24 UTC, QuanMPhm commented on src/openstack_billing_db/main.py
> +            gpu_a2=args.rate_gpu_a2_su,
@naved001 I have no idea why the A2 GPU rate is not in `nerc-rates`

2024-06-18 06:05 UTC, QuanMPhm commented
@naved001 I've applied your comments so far, and will wait for further instructions for the missing A2 GPU rate.

2024-06-18 12:25 UTC, joachimweyl commented on src/openstack_billing_db/main.py
> +            gpu_a2=args.rate_gpu_a2_su,
Please update `rates.yaml` with an A2 value. A2 costs the same as K80s.

2024-06-18 17:48 UTC, naved001 commented on src/openstack_billing_db/main.py
> +            gpu_a2=args.rate_gpu_a2_su,
Here's a PR: https://github.com/CCI-MOC/nerc-rates/pull/8

2024-06-21 02:57 UTC, QuanMPhm commented on src/openstack_billing_db/main.py
> +            gpu_a2=args.rate_gpu_a2_su,
I've used the A2 GPU rate from `nerc-rates`

2024-06-21 14:25 UTC, naved001 approved these changes

2024-06-24 15:10 UTC, knikolla approved these changes

2024-06-24 15:10 UTC, merged